channel:
    - currentsecret: null
      endpoint: https://api.openai-sb.com
      excludemodels: []
      group: []
      hitmodels:
        - gpt-3.5-turbo
        - gpt-3.5-turbo-instruct
        - gpt-3.5-turbo-0613
        - gpt-3.5-turbo-0301
        - gpt-3.5-turbo-1106
        - gpt-3.5-turbo-0125
        - gpt-3.5-turbo-16k
        - gpt-3.5-turbo-16k-0613
        - gpt-3.5-turbo-16k-0301
        - gpt-4
        - gpt-4-0314
        - gpt-4-0613
        - gpt-4-1106-preview
        - gpt-4-0125-preview
        - gpt-4-turbo-preview
        - gpt-4-vision-preview
        - gpt-4-1106-vision-preview
        - gpt-4-32k
        - gpt-4-32k-0314
        - gpt-4-32k-0613
        - dalle
        - dall-e-2
        - dall-e-3
      id: 1
      mapper: ""
      models:
        - gpt-3.5-turbo
        - gpt-3.5-turbo-instruct
        - gpt-3.5-turbo-0613
        - gpt-3.5-turbo-0301
        - gpt-3.5-turbo-1106
        - gpt-3.5-turbo-0125
        - gpt-3.5-turbo-16k
        - gpt-3.5-turbo-16k-0613
        - gpt-3.5-turbo-16k-0301
        - gpt-4
        - gpt-4-0314
        - gpt-4-0613
        - gpt-4-1106-preview
        - gpt-4-0125-preview
        - gpt-4-turbo-preview
        - gpt-4-vision-preview
        - gpt-4-1106-vision-preview
        - gpt-4-32k
        - gpt-4-32k-0314
        - gpt-4-32k-0613
        - dalle
        - dall-e-2
        - dall-e-3
      name: gpt
      priority: 0
      proxy:
        password: ""
        proxy: ""
        proxytype: 0
        username: ""
      reflect: {}
      retry: 1
      secret: sb-21bf70d122a55c2b984b794295d7aa7d0b8ee71d8512e8a4
      state: true
      type: openai
      weight: 1
charge:
    - anonymous: false
      id: 1
      input: 1
      models:
        - gpt-3.5-turbo
        - gpt-3.5-turbo-0613
        - gpt-3.5-turbo-1106
        - gpt-3.5-turbo-16k
        - gpt-3.5-turbo-0125
        - gpt-3.5-turbo-0301
        - gpt-3.5-turbo-16k-0613
        - gpt-3.5-turbo-instruct
        - gpt-3.5-turbo-16k-0301
        - dalle
        - dall-e-2
        - dall-e-3
        - claude-instant-1.2
        - claude-2
        - claude-2.1
        - claude-3-opus-20240229
        - claude-3-sonnet-20240229
        - claude-3-haiku-20240307
        - claude-slack
        - spark-desk-v1.5
        - spark-desk-v2
        - spark-desk-v3
        - spark-desk-v3.5
        - glm-4
      output: 1
      type: token-billing
      unset: false
    - anonymous: false
      id: 2
      input: 3
      models:
        - gpt-4
        - gpt-4-0314
        - gpt-4-0613
        - gpt-4-1106-preview
        - gpt-4-0125-preview
        - gpt-4-turbo-preview
        - gpt-4-vision-preview
        - gpt-4-1106-vision-preview
        - gpt-4-32k
        - gpt-4-32k-0314
        - gpt-4-32k-0613
        - glm-4v
      output: 3
      type: token-billing
      unset: false
mysql:
    db: uniai
    host: localhost
    password: JSyKb5P2nxN5xwwA
    port: 3306
    tls: false
    user: uniai
redis:
    db: "0"
    host: localhost
    password: ""
    port: "6379"
secret: secret
serve_static: "true"
server:
    port: 80
system:
    general:
        title: UNIAI
        description: 一站式聚合AI聊天平台
        logo: ""
        backend: ""
        file: ""
        docs: http://localhost/admin/system
        pwamanifest: |
            {
                "name": "Chat Nio",
                "short_name": "Chat Nio",
                "icons": [
                  {
                    "src": "/service/android-chrome-192x192.png",
                    "sizes": "192x192",
                    "type": "image/png"
                  },
                  {
                    "src": "/service/android-chrome-512x512.png",
                    "sizes": "512x512",
                    "type": "image/png"
                  }
                ],
                "start_url": "/",
                "theme_color": "#000000",
                "background_color": "#0000000",
                "display": "standalone"
            }
        debugmode: false
    site:
        closeregister: false
        closerelay: false
        relayplan: false
        quota: 10
        buylink: ""
        announcement: ""
        contact: 联系人123456
        footer: 保留所有权
        authfooter: false
    mail:
        host: smtp-mail.outlook.com
        port: 587
        username: uniai_official
        password: Yjy1993!
        from: uniai_official@outlook.com
        whitelist:
            enabled: true
            custom: ""
            whitelist:
                - gmail.com
                - outlook.com
                - yahoo.com
                - hotmail.com
                - foxmail.com
                - icloud.com
                - qq.com
                - 163.com
                - 126.com
    search:
        endpoint: https://duckduckgo-api.vercel.app
        query: 5
    common:
        article: []
        generation: []
        cache: []
        expire: 0
        size: 0
        imagestore: false
